title: 학습 정리 블로그
description: 학습 정리 블로그
author: Dongmin
email: ihaha424@gmail.com
theme: jekyll-theme-hacker
markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed

# GitHub Pages compatibility
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
