title: 개발 노트
description: 학습 기록
author: Dongmin
theme: jekyll-theme-hacker
markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

permalink: /:categories/:title
